# Minimal Docker Compose - Uses existing host Neo4j and Ollama
# Perfect for development when you already have services running
# Usage: docker-compose -f docker-compose.minimal.yml up -d

services:
  # Only the MCP Server - connects to host services
  mcp-server:
    build: .
    container_name: borg-mcp-server
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - NEO4J_URI=bolt://host.docker.internal:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-memento_password}
      - LOCAL_EMBEDDING_URL=http://host.docker.internal:11434/api/embeddings
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    extra_hosts:
      - "host.docker.internal:host-gateway"
