version: '3.8'

services:
  # Borg Collective Memory MCP Server
  mcp-server:
    build: .
    container_name: borg-mcp-server
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-memento_password}
      - LOCAL_EMBEDDING_URL=http://ollama:11434/api/embeddings
    depends_on:
      neo4j:
        condition: service_healthy
      ollama:
        condition: service_started
    networks:
      - borg-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Neo4j Database
  neo4j:
    image: neo4j:5.22-community
    container_name: borg-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-memento_password}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_memory_heap_initial__size=512M
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    networks:
      - borg-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Ollama for Embeddings
  ollama:
    image: ollama/ollama:latest
    container_name: borg-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - borg-network
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # Ollama Model Puller (init container)
  ollama-init:
    image: ollama/ollama:latest
    container_name: borg-ollama-init
    depends_on:
      - ollama
    networks:
      - borg-network
    entrypoint: /bin/sh
    command:
      - -c
      - |
        echo "Waiting for Ollama to be ready..."
        sleep 10
        echo "Pulling nomic-embed-text model..."
        ollama pull nomic-embed-text
        echo "Model ready!"
    restart: "no"

networks:
  borg-network:
    driver: bridge

volumes:
  neo4j-data:
    driver: local
  neo4j-logs:
    driver: local
  ollama-data:
    driver: local
